import { supabase } from './supabase-client.mjs'

const today = '2026-03-17'

const picks = [
  {
    id: 'pick-2026-03-17-001',
    match_date: today,
    league: 'Champions League',
    league_flag: '🏆',
    home_team: 'Arsenal',
    away_team: 'Bayer Leverkusen',
    kick_off: '21:00',
    prediction_type: '1',
    prediction_value: 'Arsenal pobeda',
    confidence: 5,
    reasoning: 'Arsenal 8-0 u Ligi šampiona ove sezone kod kuće. Leverkusen prošao kroz playoff i pokazao slabosti u gostima. Prvi meč završen 1-1 (Havertz gol u 89 min). Arsenal dominira na Emirates-u sa neverovatnom defanzivnom disciplinom. Arteta ima taktičku prednost — očekujemo kontrolisanu pobedu.',
    odds: 1.55,
    bookmaker: '1xBet',
    affiliate_url: 'https://1xbet.com',
    result: 'pending',
    is_free: false,
    sport: 'football',
    value_edge: 8.5
  },
  {
    id: 'pick-2026-03-17-002',
    match_date: today,
    league: 'Champions League',
    league_flag: '🏆',
    home_team: 'Arsenal',
    away_team: 'Bayer Leverkusen',
    kick_off: '21:00',
    prediction_type: 'Hendikep',
    prediction_value: 'Arsenal -1.5',
    confidence: 4,
    reasoning: 'Arsenal treba ubedljivu pobedu za prolaz. Leverkusen ima slabu odbranu u gostima u nokaut fazi. Arsenalova napadačka moć kod kuće (prosek 2.5 gola po meču u LŠ) sugeriše pobedu sa razlikom. Očekujemo 2-0 ili 3-0.',
    odds: 2.20,
    bookmaker: '1xBet',
    affiliate_url: 'https://1xbet.com',
    result: 'pending',
    is_free: false,
    sport: 'football',
    value_edge: 6.2
  },
  {
    id: 'pick-2026-03-17-003',
    match_date: today,
    league: 'Champions League',
    league_flag: '🏆',
    home_team: 'Manchester City',
    away_team: 'Real Madrid',
    kick_off: '21:00',
    prediction_type: 'Over',
    prediction_value: 'Over 3.5 golova',
    confidence: 4,
    reasoning: 'City gubi 0-3 iz prvog meča i MORA da napadne od prvog minuta. Haaland ima 7 golova u 9 LŠ mečeva ove sezone. Real dobija nazad Mbappea i Bellinghama — devastirajući kontranapad sa Viniciusom. Svaki Cityjev napad ostavlja prostor iza. Recept za goleadu.',
    odds: 2.10,
    bookmaker: '1xBet',
    affiliate_url: 'https://1xbet.com',
    result: 'pending',
    is_free: true,
    sport: 'football',
    value_edge: 7.1
  },
  {
    id: 'pick-2026-03-17-004',
    match_date: today,
    league: 'Champions League',
    league_flag: '🏆',
    home_team: 'Manchester City',
    away_team: 'Real Madrid',
    kick_off: '21:00',
    prediction_type: 'BTTS',
    prediction_value: 'Oba tima daju gol',
    confidence: 5,
    reasoning: 'City napada totalno — Haaland, Foden, Cherki u napadu. Real kontrira sa Mbappe + Vinicius (3 gola, 5 asistencija u LŠ). Istorijski prosek: City 58.2% posed, Real 5.5 šuteva u okvir po meču. Obostrani golovi su praktično garantovani u ovom scenariju.',
    odds: 1.45,
    bookmaker: '1xBet',
    affiliate_url: 'https://1xbet.com',
    result: 'pending',
    is_free: true,
    sport: 'football',
    value_edge: 9.3
  },
  {
    id: 'pick-2026-03-17-005',
    match_date: today,
    league: 'Champions League',
    league_flag: '🏆',
    home_team: 'Sporting CP',
    away_team: 'Bodø/Glimt',
    kick_off: '18:45',
    prediction_type: 'Over',
    prediction_value: 'Over 2.5 golova',
    confidence: 4,
    reasoning: 'Sporting gubi 0-3 iz prvog meča i mora da napadne svom silinom. U prvom meču bilo ukupno 21 šut. Bodo je klinčan u kontri — dokazali sa 3 gola u prvoj utakmici. Sporting kod kuće prosečno daje 2.1 gol po meču. Očekujemo minimum 3 gola.',
    odds: 1.55,
    bookmaker: '1xBet',
    affiliate_url: 'https://1xbet.com',
    result: 'pending',
    is_free: false,
    sport: 'football',
    value_edge: 5.8
  },
  {
    id: 'pick-2026-03-17-006',
    match_date: today,
    league: 'Champions League',
    league_flag: '🏆',
    home_team: 'Sporting CP',
    away_team: 'Bodø/Glimt',
    kick_off: '18:45',
    prediction_type: '1',
    prediction_value: 'Sporting pobeda',
    confidence: 4,
    reasoning: 'Sporting je imao 51% poseda u prvom meču i bio bolji tim po statistici, ali Bodo je bio kliničan. Kod kuće na Estadio Jose Alvalade, Sporting je drugačiji tim. Trincao i Suarez predvode napad. Pobeda verovatna ali nedovoljna za prolaz.',
    odds: 1.35,
    bookmaker: '1xBet',
    affiliate_url: 'https://1xbet.com',
    result: 'pending',
    is_free: false,
    sport: 'football',
    value_edge: 4.2
  },
  {
    id: 'pick-2026-03-17-007',
    match_date: today,
    league: 'Champions League',
    league_flag: '🏆',
    home_team: 'Chelsea',
    away_team: 'PSG',
    kick_off: '21:00',
    prediction_type: '1',
    prediction_value: 'Chelsea pobeda',
    confidence: 3,
    reasoning: 'Chelsea gubi 2-5 ali Stamford Bridge je tvrdjava. PSG ne mora da forsira — dovoljno im je da ne izgube. To znači da će Chelsea dominirati posedom i napadati. Enzo Fernandez u odličnoj formi (gol u prvom meču). Value pik sa kvotom 2.15.',
    odds: 2.15,
    bookmaker: '1xBet',
    affiliate_url: 'https://1xbet.com',
    result: 'pending',
    is_free: false,
    sport: 'football',
    value_edge: 5.1
  },
  {
    id: 'pick-2026-03-17-008',
    match_date: today,
    league: 'Champions League',
    league_flag: '🏆',
    home_team: 'Chelsea',
    away_team: 'PSG',
    kick_off: '21:00',
    prediction_type: 'Over',
    prediction_value: 'Over 2.5 golova',
    confidence: 4,
    reasoning: 'Chelsea mora da postigne minimum 4 gola za prolaz — totalni napad od prvog minuta. PSG ima Kvaratskheliju i Vitinhu koji su smrtonosni u kontri. Prvi meč imao 7 golova. Očekujemo sličan scenarijo — minimum 3 gola.',
    odds: 1.60,
    bookmaker: '1xBet',
    affiliate_url: 'https://1xbet.com',
    result: 'pending',
    is_free: false,
    sport: 'football',
    value_edge: 6.7
  },
  {
    id: 'pick-2026-03-17-009',
    match_date: today,
    league: 'Champions League',
    league_flag: '🏆',
    home_team: 'Arsenal',
    away_team: 'Bayer Leverkusen',
    kick_off: '21:00',
    prediction_type: 'Under',
    prediction_value: 'Under 3.5 golova',
    confidence: 4,
    reasoning: 'Arsenal kontroliše tempo kao niko u Evropi. Arteta ne dopušta kontre — prosečno primaju 0.4 gola po meču u LŠ kod kuće. Leverkusen bez pravih šansi u gostima. Očekujemo kontrolisan meč: 2-0 ili 2-1. Under 3.5 je siguran.',
    odds: 1.50,
    bookmaker: '1xBet',
    affiliate_url: 'https://1xbet.com',
    result: 'pending',
    is_free: false,
    sport: 'football',
    value_edge: 5.5
  },
  {
    id: 'pick-2026-03-17-010',
    match_date: today,
    league: 'Champions League',
    league_flag: '🏆',
    home_team: 'Manchester City',
    away_team: 'Real Madrid',
    kick_off: '21:00',
    prediction_type: '1',
    prediction_value: 'Man City pobeda',
    confidence: 3,
    reasoning: 'City kod kuće sa Haalandom, Fodenom i Cherkijem. Etihad atmosfera plus očaj od 0-3 — Guardiola će izvući maksimum. Istorijski City ima blagu prednost kod kuće vs Real (prosek 58% posed). Pobeda verovatna ali prolaz teško. Odličan value na kvoti 2.00.',
    odds: 2.00,
    bookmaker: '1xBet',
    affiliate_url: 'https://1xbet.com',
    result: 'pending',
    is_free: false,
    sport: 'football',
    value_edge: 4.8
  }
]

const { data, error } = await supabase.from('picks').upsert(picks)
if (error) {
  console.log('ERROR:', JSON.stringify(error, null, 2))
} else {
  console.log('SUCCESS: ' + picks.length + ' picks inserted!')
}
process.exit()
