import { supabase } from './supabase-client.mjs';

const today = '2026-03-19';

// Delete today's pending picks
const { error: delErr } = await supabase.from('picks').delete().eq('result', 'pending').gte('match_date', today);
if (delErr) console.log('Delete error:', delErr);
else console.log('Deleted existing pending picks for today');

const picks = [
  // PREMIUM PICKS (4-5 stars)
  {
    id: 'pick-2026-03-19-01',
    sport: 'basketball',
    league: 'NBA',
    league_flag: '🏀',
    home_team: 'San Antonio Spurs',
    away_team: 'Phoenix Suns',
    match_date: '2026-03-19',
    kick_off: '01:00',
    prediction_type: 'Pobednik',
    prediction_value: 'San Antonio Spurs ML',
    odds: 1.275,
    bookmaker: '1xBet',
    confidence: 5,
    is_free: false,
    is_sigurica: true,
    result: 'pending',
    value_edge: 7.0,
    reasoning: 'San Antonio (51-18) je druga sila Zapada i igraju kod kuće gde su dominantni. Victor Wembanyama je u fantastičnoj formi — Spursi su upravo uništili Sacramento 132-104 u gostima. Phoenix (39-30) dolazi sa poraza od Minnesote 104-116 i ima problema sa konzistentnošću u gostima. Spursi su 7.52 SRS (drugi najbolji u NBA), dok Suns imaju 1.25 SRS. Kvota 1.275 odgovara ~78% verovatnoće, realna šansa Spursa je ~85% → value edge ~7%. Ovo je sigurica večeri.',
    reasoning_en: "San Antonio (51-18) is the 2nd seed in the West playing at home where they dominate. Victor Wembanyama is in fantastic form — Spurs just destroyed Sacramento 132-104 on the road. Phoenix (39-30) comes off a loss to Minnesota 104-116 and struggles with consistency away. Spurs SRS 7.52 (2nd best in NBA) vs Suns 1.25. Odds 1.275 imply ~78% probability, real Spurs chance is ~85% → ~7% value edge. Tonight's lock pick.",
    created_at: new Date().toISOString()
  },
  {
    id: 'pick-2026-03-19-02',
    sport: 'basketball',
    league: 'NBA',
    league_flag: '🏀',
    home_team: 'Charlotte Hornets',
    away_team: 'Orlando Magic',
    match_date: '2026-03-19',
    kick_off: '00:00',
    prediction_type: 'Pobednik',
    prediction_value: 'Charlotte Hornets ML',
    odds: 1.484,
    bookmaker: '1xBet',
    confidence: 4,
    is_free: false,
    is_sigurica: false,
    result: 'pending',
    value_edge: 5.0,
    reasoning: 'Charlotte (35-34) igra kod kuće gde imaju odličan bilans 20-16. Upravo su razbili Miami 136-106 pre dva dana u impresivnoj predstavi. Orlando (38-30) dolazi sa poraza od OKC (108-113) i ima problema na gostovanjima. Charlotte ima SRS 3.14 što pokazuje da su kompetitivan tim, a favoriti su sa spreadom -5.5. Kvota 1.484 odgovara ~67% verovatnoće, procenjujem realnu šansu na ~72% → value edge 5%.',
    reasoning_en: "Charlotte (35-34) plays at home with a strong 20-16 home record. They just destroyed Miami 136-106 two days ago. Orlando (38-30) comes off a loss to OKC (108-113) and struggles on the road. Charlotte SRS 3.14 shows competitiveness, and they're -5.5 favorites. Odds 1.484 imply ~67% probability, real chance ~72% → 5% value edge.",
    created_at: new Date().toISOString()
  },
  {
    id: 'pick-2026-03-19-03',
    sport: 'basketball',
    league: 'NBA',
    league_flag: '🏀',
    home_team: 'Miami Heat',
    away_team: 'Los Angeles Lakers',
    match_date: '2026-03-19',
    kick_off: '01:00',
    prediction_type: 'Pobednik',
    prediction_value: 'Miami Heat ML',
    odds: 1.668,
    bookmaker: '1xBet',
    confidence: 4,
    is_free: false,
    is_sigurica: false,
    result: 'pending',
    value_edge: 8.0,
    reasoning: 'Miami (38-31) igra kod kuće gde su solidni. KLJUČNI FAKTOR: Lakers (44-25) igraju back-to-back! Sinoć su igrali u Houstonu (pobeda 124-116), a Dončić je imao 40 poena. Umor je realan faktor. Miami je odmorena ekipa sa jakom odbranom kod kuće (SRS 3.28). Lakers na B2B u gostima drastično padaju u učinku. Kvota 1.668 odgovara ~60% verovatnoće, sa B2B faktorom procena je ~68% → value edge 8%.',
    reasoning_en: "Miami (38-31) at home. KEY FACTOR: Lakers (44-25) on a back-to-back! They played in Houston last night (124-116 win) with Doncic scoring 40. Fatigue is real. Miami is rested with strong home defense (SRS 3.28). Lakers on B2B away games drop significantly. Odds 1.668 imply ~60% probability, with B2B factor real chance ~68% → 8% value edge.",
    created_at: new Date().toISOString()
  },
  {
    id: 'pick-2026-03-19-04',
    sport: 'tennis',
    league: 'ATP Miami Open',
    league_flag: '🎾',
    home_team: 'Fabian Marozsan',
    away_team: 'Joao Fonseca',
    match_date: '2026-03-19',
    kick_off: '19:10',
    prediction_type: 'Pobednik',
    prediction_value: 'Joao Fonseca ML',
    odds: 1.392,
    bookmaker: '1xBet',
    confidence: 4,
    is_free: false,
    is_sigurica: false,
    result: 'pending',
    value_edge: 4.0,
    reasoning: 'Joao Fonseca (WR #39) je jedan od najuzbudljivijih mladih igrača na turu. Na hard courtu u Majamiju bi trebalo da dominira protiv Marozsana (WR #46). Fonseca ima ekspanzivan stil igre koji odgovara brzim uslovima u Majamiju. Marozsan ove sezone ima 6-6 bilans bez titule, dok Fonseca iako 4-4 pokazuje veći potencijal. 1xBet jasno favorizuje Fonseku. Kvota 1.392 odgovara ~72% šanse, procena ~76% → edge 4%.',
    reasoning_en: "Joao Fonseca (WR #39) is one of the most exciting young players on tour. On Miami hard courts he should dominate Marozsan (WR #46). Fonseca's expansive game suits fast Miami conditions. Marozsan is 6-6 this season with no title, while Fonseca shows higher ceiling despite 4-4 record. 1xBet clearly favors Fonseca. Odds 1.392 imply ~72%, estimate ~76% → 4% edge.",
    created_at: new Date().toISOString()
  },
  {
    id: 'pick-2026-03-19-05',
    sport: 'tennis',
    league: 'ATP Miami Open',
    league_flag: '🎾',
    home_team: 'Raphael Collignon',
    away_team: 'Grigor Dimitrov',
    match_date: '2026-03-19',
    kick_off: '19:20',
    prediction_type: 'Pobednik',
    prediction_value: 'Grigor Dimitrov ML',
    odds: 1.749,
    bookmaker: '1xBet',
    confidence: 4,
    is_free: false,
    is_sigurica: false,
    result: 'pending',
    value_edge: 8.0,
    reasoning: 'Grigor Dimitrov je iskusni veteran sa ogromnim iskustvom na Masters turnirima. Raphael Collignon je niže rangiran igrač koji nema iskustva na ovakvim pozornicama. Dimitrov se odlično snalazi na hard courtu i u Majamiju tradicionalno igra dobro. Kvota 1.749 odgovara ~57% verovatnoće, ali realna šansa Dimitrova je ~65% → value edge 8%. Odličan value bet.',
    reasoning_en: "Grigor Dimitrov is an experienced veteran with huge Masters tournament pedigree. Raphael Collignon is a lower-ranked player lacking experience at this level. Dimitrov excels on hard courts and traditionally plays well in Miami. Odds 1.749 imply ~57% probability, but real Dimitrov chance is ~65% → 8% value edge. Excellent value bet.",
    created_at: new Date().toISOString()
  },
  {
    id: 'pick-2026-03-19-06',
    sport: 'football',
    league: 'UEFA Europa League',
    league_flag: '⚽',
    home_team: 'Real Betis',
    away_team: 'Panathinaikos',
    match_date: '2026-03-19',
    kick_off: '21:00',
    prediction_type: 'Pobednik',
    prediction_value: 'Real Betis ML',
    odds: 1.443,
    bookmaker: '1xBet',
    confidence: 4,
    is_free: false,
    is_sigurica: false,
    result: 'pending',
    value_edge: 6.0,
    reasoning: 'Real Betis igra kod kuće na Estadio Benito Villamarin u revanš meču osmine finala Lige Evrope. Betis je kvalitetniji tim iz La Lige sa jakom odbranom — 4 od poslednjih 5 utakmica su imale manje od 3 gola. Panathinaikos iz Grčke ima mnogo manji budžet i kvalitet. Betis kod kuće u evropskim utakmicama igra čvrsto i fokusirano. Kvota 1.443 odgovara ~69% šanse, procena ~75% → edge 6%.',
    reasoning_en: "Real Betis at home at Estadio Benito Villamarin in the Europa League Round of 16 2nd leg. Betis is the higher quality La Liga side with strong defense — 4 of last 5 matches had under 3 goals. Panathinaikos from Greece has much smaller budget and quality. Betis at home in European matches plays tight and focused. Odds 1.443 imply ~69%, estimate ~75% → 6% edge.",
    created_at: new Date().toISOString()
  },
  // FREE PICKS (3 stars)
  {
    id: 'pick-2026-03-19-07',
    sport: 'basketball',
    league: 'NBA',
    league_flag: '🏀',
    home_team: 'Utah Jazz',
    away_team: 'Milwaukee Bucks',
    match_date: '2026-03-19',
    kick_off: '02:00',
    prediction_type: 'Pobednik',
    prediction_value: 'Milwaukee Bucks ML',
    odds: 1.476,
    bookmaker: '1xBet',
    confidence: 3,
    is_free: true,
    is_sigurica: false,
    result: 'pending',
    value_edge: 3.0,
    reasoning: 'Milwaukee (28-40) je favorit u gostima protiv najgoreg tima Zapada Utah Jazz (20-49). Bucks imaju Giannisa koji može dominirati protiv slabe Jazzove odbrane. Jazz je izgubio od Minnesote 111-147 sinoć! Ipak, Milwaukee i sam ima loš bilans ove sezone i nije pouzdana ekipa — zato 3⭐ confidence.',
    reasoning_en: "Milwaukee (28-40) favored away against the worst West team Utah Jazz (20-49). Bucks have Giannis who can dominate Jazz weak defense. Jazz lost to Minnesota 111-147 last night! However, Milwaukee itself has a poor record this season and is not reliable — hence 3-star confidence.",
    created_at: new Date().toISOString()
  },
  {
    id: 'pick-2026-03-19-08',
    sport: 'tennis',
    league: 'ATP Miami Open',
    league_flag: '🎾',
    home_team: 'Emilio Nava',
    away_team: 'Tomas Machac',
    match_date: '2026-03-19',
    kick_off: '21:40',
    prediction_type: 'Pobednik',
    prediction_value: 'Tomas Machac ML',
    odds: 1.443,
    bookmaker: '1xBet',
    confidence: 3,
    is_free: true,
    is_sigurica: false,
    result: 'pending',
    value_edge: 3.0,
    reasoning: 'Tomas Machac je viši rangiran igrač sa iskustvom na ATP turu. Emilio Nava je lokalni američki igrač ali nema isti kvalitet. Machac je dobar na hard courtu, ali forma mu varira ove sezone. Kvota 1.443 je OK ali ne nudi premium value — zato free pick sa 3⭐.',
    reasoning_en: "Tomas Machac is higher ranked with ATP tour experience. Emilio Nava is a local American player but lacks the same quality. Machac is good on hard court but form varies this season. Odds 1.443 decent but not premium value — hence free pick at 3-star.",
    created_at: new Date().toISOString()
  },
  {
    id: 'pick-2026-03-19-09',
    sport: 'football',
    league: 'UEFA Europa League',
    league_flag: '⚽',
    home_team: 'SC Freiburg',
    away_team: 'KRC Genk',
    match_date: '2026-03-19',
    kick_off: '21:00',
    prediction_type: 'Pobednik',
    prediction_value: 'SC Freiburg ML',
    odds: 1.617,
    bookmaker: '1xBet',
    confidence: 3,
    is_free: true,
    is_sigurica: false,
    result: 'pending',
    value_edge: 4.0,
    reasoning: 'Freiburg igra kod kuće u Bundesliga sredini gde su solidna ekipa. Genk iz Belgije je dobar ali ne na nivou nemačkog prvoligaša na njegovom terenu. Revanš meč gde Freiburg želi da obezbedi prolaz. Ipak, evropske utakmice su nepredvidive — 3⭐.',
    reasoning_en: "Freiburg at home, a solid Bundesliga mid-table team. Genk from Belgium is decent but not at the level of a German top-flight team on their home ground. 2nd leg where Freiburg wants to secure qualification. However, European matches can be unpredictable — 3-star.",
    created_at: new Date().toISOString()
  }
];

const { data, error } = await supabase.from('picks').upsert(picks);
if (error) console.log('Insert error:', JSON.stringify(error));
else console.log('Successfully inserted ' + picks.length + ' picks');
